#%RAML 1.0
---
title: Scraf
baseUri: https://scraf.pwrau.ml/api/{version}
version: v1

/students:
  get:
  post:
  /{studentId}:
    get:
    patch:
    delete:
    /subjects:
      get:
      /{subjectId}:
        /marks:
          get:

/teachers:
  get:
  post:
  /{teacherId}:
    get:
    patch:
    delete:
    /subjects:
      get:
      post:
      /{subjectId}:
        delete:
        /marks:
          get:

/school:
  get:
  post:
  /{schoolId}:
    get:
    patch:
    delete:
    /subjects:
      get:
      post:
      /{subjectId}:
        get:
        patch:
        delete:
        /marks:
          get:
          post:
          /{markId}:
            get:
            patch:
            delete:
    /classes:
      get:
      post:
      /{classId}:
        get:
        patch:
        delete:
        /subjects:
          get:
          post:
          /{subjectId}:
            delete:
  /students:
    get:
    post:
    /{studentId}:
      delete:
  /teachers:
    get:
    post:
    /{teacherId}:
      delete:
