#%RAML 1.0
---
title: Scraf
baseUri: https://scraf.pwrau.ml/api/{version}
version: v1

/students:
  type:
    collection:
      example-get-collection: |
        [
          {
            "id": 107,
            "name": "Andrea Pappacoda"
          },
          {
            "id": 238,
            "name": "Paolo Andreoli"
          }
        ]
  /{studentId}:
    type: collection-item
    /subjects:
      type: sub-collection-read
      /{subjectId}:
        /marks:
          type: sub-collection-read

/teachers:
  type: collection
  /{teacherId}:
    type: collection-item
    /subjects:
      type: sub-collection
      /{subjectId}:
        type: sub-collection-item
        /marks:
          type: sub-collection-read

/schools:
  type: collection
  post:
    responses:
      201:
        body:
          text/plain: !!null

  /{schoolId}:
    type: collection-item
    /subjects:
      type: collection
      /{subjectId}:
        type: collection-item
        /marks:
          type: collection
          /{markId}:
            type: collection-item
    /classes:
      type: collection
      /{classId}:
        type: collection-item
        /subjects:
          type: sub-collection
          /{subjectId}:
            type: sub-collection-read
        /students:
          /{studentId}:
        /teachers:
          /{teacherId}:
  /students:
    type: sub-collection
    /{studentId}:
      type: sub-collection-item
  /teachers:
    type: sub-collection
    /{teacherId}:
      type: sub-collection-item

resourceTypes:
  collection:
    description: <<resourcePathName>> registered to Scraf
    get:
      description: Get a list of <<resourcePathName>> based on their name
      queryParameters:
        name:
          description: "Name of the <<resourcePathName|!singularize>> to search"
          type: string
          minLength: 3
          required: true
      responses:
        200:
          body:
            application/json:
              type: search-result
              example: <<example-get-collection>>
        400:
          body:
            application/json:
              type: message
              example: |
                {
                  "message": "The query must be at least 3 characters long"
                }
    post:
      description: Register a <<resourcePathName|!singularize>> and get its id
      body:
        application/json:
          type: <<resourcePathName|!singularize>>-post
      responses:
        201:
          body:
            application/json:
              type: id
              example: |
                {
                  "id": 107
                }
        400:
          body:
            application/json:
              type: message
              example: |
                {
                  "message": "The parameter \"paolo\" does not exist"
                }
  collection-item:
    get:
      description: Get details about a <<resourcePathName|!singularize>>
      responses:
        200:
          body:
            application/json:
              type: <<resourcePathName|!singularize>>
    patch:
      description: Change details about a <<resourcePathName|!singularize>>
      body:
        application/json:
          type: <<resourcePathName|!singularize>>
      responses:
        200:
        400:
          body:
            application/json:
              type: message
              example: |
                {
                  "message": "The parameter "paolo" does not exist"
                }
    delete:
      description: Delete a <<resourcePathName|!singularize>>
      responses:
        200:
  sub-collection:
    get:
      description: Get the list of <<resourcePathName>> of a particular entity
      responses: 
        200:
          body:
            application/json:
              type: id-array
              example: |
                [
                  {
                    "id": 107
                  },
                  {
                    "id": 238
                  }
                ]
    post:
  sub-collection-item:
    delete:
  sub-collection-read:
    get:

types:
  id: |
    {
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "type": "object",
      "properties": {
        "id": {
          "type": "integer"
        }
      }
    }
  id-array: |
    {
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          }
        }
      }
    }
  search-result: |
    {
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "name": {
            "type": "string"
          }
        }
      }
    }
  message: |
    {
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        }
      }
    }
  student-post: |
    {
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "type": "object",
      "properties": {
        "mail": {
          "type": "string",
          "format": "email"
        },
        "name": {
          "type": "string"
        },
        "surname": {
          "type": "string",
          "required": false
        }
      }
    }
  teacher-post: |
    {
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "type": "object",
      "properties": {
        "mail": {
          "type": "string",
          "format": "email"
        },
        "name": {
          "type": "string"
        },
        "surname": {
          "type": "string"
        }
      }
    }
  school-post: |
    {
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "type": "object",
      "properties": {
        "code": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      }
    }
  class-post: |
    {
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        }
      }
    }
  subject-post: |
    {
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        }
      }
    }
  student: |
    {
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "type": "object",
      "properties": {
        "mail": {
          "type": "string",
          "format": "email"
        },
        "name": {
          "type": "string"
        },
        "surname": {
          "type": "string"
        },
        "is_class_president": {
          "type": "boolean",
          "required": false
        },
        "is_school_president": {
          "type": "boolean",
          "required": false
        }
      }
    }
  teacher: |
    {
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "type": "object",
      "properties": {
        "mail": {
          "type": "string",
          "format": "email"
        },
        "name": {
          "type": "string"
        },
        "surname": {
          "type": "string"
        },
        "is_class_coordinator": {
          "type": "boolean",
          "required": false
        },
        "is_school_president": {
          "type": "boolean",
          "required": false
        }
      }
    }
  school: |
    {
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        }
      }
    }
  class: |
    {
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        }
      }
    }
  subject: |
    {
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        }
      }
    }
