name: Publish API spec

on:
  push:
    branches: [ main ]
    paths:
      - scraf.raml
      - .github/workflows/raml-gh-pages.yaml

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Install raml2html
        run: |
          sudo rm -r /etc/apt/sources.list* && sudo mkdir /etc/apt/sources.list.d
          printf "Enabled: yes\nTypes: deb\nURIs: http://azure.archive.ubuntu.com/ubuntu/\nSuites: focal focal-updates focal-security\nComponents: main universe\n" | sudo tee /etc/apt/sources.list.d/system.sources
          sudo apt-get -qq update && sudo apt-get -qq install --assume-yes --no-install-recommends yarnpkg
          sudo yarnpkg global add --silent --non-interactive raml2html

      - name: Build webpage from RAML file
        run: |
          mkdir gh-pages
          raml2html scraf.raml --output gh-pages/index.html

      - name: Publish page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages
          cname: api.scraf.pwrau.ml
